### ISSUE TITLE
MacBook Pro 13" 2018 - 15,2

### ISSUE THREAD

**Issue by ThisIsNoahEvans** [Dunedan/mbp-2016-linux#151]
Any news on the 15,2? Just wondering as some other newer models have support. Thanks!

**Comment by Dunedan** [comment]
Please don't open issues with such generic questions. The purpose of this repository is to discuss and document how to get individual components running and to document the status of upstreaming required fixes for that. The reason the 15,x models aren't covered in the overview yet is because nobody provided a good enough PR adding information about them yet. There are however already multiple open issues discussing different aspects of hardware support for 15,x models.
